ToyStory4/Controllers/CodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ToyStory4.Controllers
{
    public class CodeController : Controller
    {
        // GET: Code
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Valid()
        {
            return View();
        }
    }
}

ToyStory4/Controllers/es_ESController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using ToyStory4.Service;

namespace ToyStory4.Controllers
{
    public class es_ESController : Controller
    {

        public JsonResult GetId(string id)
        {                       
            CodeService _codeService = new CodeService();
            var _result = false;
            if (!string.IsNullOrEmpty(Session["codigo_cod"] as string) &&
                !string.IsNullOrEmpty(((int)Session["id_cod"]).ToString() as string))
            {
                _result = _codeService.UpdateValidatedCode((string)Session["codigo_cod"], (int)Session["id_cod"], id);
            }       
            var data = "";
            if (_result)
            {
                data = "{ \"codigo_cod\" : \"" + (string)Session["codigo_cod"] + " \" , \"id_cod\" : \"" + ((int)Session["id_cod"]).ToString() + "\" , \"IdKellogs\" : \"" + id + "\" }";
            }
            else {
                data = "{ \"codigo_cod\" : \"error\"}";
            }
            return Json(data, JsonRequestBehavior.AllowGet); 
        }


        DateTime _fechaPromo = Convert.ToDateTime(WebConfigurationManager.AppSettings["FechaPromo"]);
        public ActionResult Index()
        {
            if (_fechaPromo <= DateTime.Now)
                return View("~/Views/es_ES/Code/DateInvalid.cshtml");
            return View();
        }

        public ActionResult Congrats()
        {

            return View();
        }
        public ActionResult Sorry()
        {

            return View();
        }

        public ActionResult Login()
        {

            return View();
        }

        public ActionResult Register()
        {

            return View();
        }

        public ActionResult ValidateCode(string codigo_cod)
        {
            CodeService _codeService = new CodeService();
            var _result = _codeService.ValidateCode(codigo_cod);
            
            if (_fechaPromo <= DateTime.Now)
                return View("~/Views/es_ES/Code/DateInvalid.cshtml");

            if (_result.Codigo_cod != null)
            {
                Session["codigo_cod"] = codigo_cod;
                Session["id_cod"] = _result.Id_cod;
                return View("~/Views/es_ES/Code/Valid.cshtml");
              
            }        
                return View("~/Views/es_ES/Code/Invalid.cshtml");                                    
        }

        

    }
}

ToyStory4/Controllers/pt_PTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using ToyStory4.Service;

namespace ToyStory4.Controllers
{
    public class pt_PTController : Controller
    {

        public JsonResult GetId(string id)
        {                       
            CodeService _codeService = new CodeService();
            var _result = false;
            if (!string.IsNullOrEmpty(Session["codigo_cod"] as string) &&
                !string.IsNullOrEmpty(((int)Session["id_cod"]).ToString() as string))
            {
                _result = _codeService.UpdateValidatedCode((string)Session["codigo_cod"], (int)Session["id_cod"], id);
            }       
            var data = "";
            if (_result)
            {
                data = "{ \"codigo_cod\" : \"" + (string)Session["codigo_cod"] + " \" , \"id_cod\" : \"" + ((int)Session["id_cod"]).ToString() + "\" , \"IdKellogs\" : \"" + id + "\" }";
            }
            else {
                data = "{ \"codigo_cod\" : \"error\"}";
            }
            return Json(data, JsonRequestBehavior.AllowGet); 
        }


        DateTime _fechaPromo = Convert.ToDateTime(WebConfigurationManager.AppSettings["FechaPromo"]);
        public ActionResult Index()
        {
            if (_fechaPromo <= DateTime.Now)
                return View("~/Views/pt_PT/Code/DateInvalid.cshtml");
            return View();
        }

        public ActionResult Congrats()
        {

            return View();
        }
        public ActionResult Sorry()
        {

            return View();
        }

        public ActionResult Login()
        {

            return View();
        }

        public ActionResult Register()
        {

            return View();
        }

        public ActionResult ValidateCode(string codigo_cod)
        {
            CodeService _codeService = new CodeService();
            var _result = _codeService.ValidateCode(codigo_cod);
            
            if (_fechaPromo <= DateTime.Now)
                return View("~/Views/pt_PT/Code/DateInvalid.cshtml");

            if (_result.Codigo_cod != null)
            {
                Session["codigo_cod"] = codigo_cod;
                Session["id_cod"] = _result.Id_cod;
                return View("~/Views/pt_PT/Code/Valid.cshtml");
              
            }        
                return View("~/Views/pt_PT/Code/Invalid.cshtml");                                    
        }

        

    }
}

ToyStory4/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ToyStory4/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ToyStory4/Views/HomePT/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ToyStory4/Views/HomePT/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ToyStory4/Views/es_ES/Code/Invalid.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Código Incorrecto | Consigue tus pegatinas gratis | Kellogg's</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1">
    <meta name="robots" value="noindex" />

    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/img/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/Content/css/bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/styles.css">
    <style type="text/css">
        .txtsubIndex {
            margin: 60px auto 35px auto
        }

        .divindex {
            margin-bottom: 40px
        }
    </style>
</head>
<body>
    <div class="content  contentKellogs">
        <div class="container containerKellogs">
            <div class="divindex">
                <div class="logo"><img src="~/Content/img/logo.png" alt="Kellog's" clasS="img-fluid" /></div>

                <div class="txtsubIndex">Tu codigo es incorreto, comprueba que lo has escrito correctamente.</div>
                @Html.ActionLink("Volver","Index","es_ES",null,new { @class="btn btnEnviar"})
            </div>
            <div class="imgpegat"><img src="~/Content/img/pegatinas.png" alt="pegatinas gratis" /></div>
            <div class="imgpegat_tablet"><img src="~/Content/img/pegatinas_tablet.png" alt="pegatinas gratis" class="img-fluid" /></div>
            <div class="imgpegat_smart"><img src="~/Content/img/pegatinas_smart.png" alt="pegatinas gratis" class="img-fluid" /></div>
        </div>
        <div id="imgcoc"><img src="~/Content/img/cocina.png" alt="cocina disney"></div>
    </div>

    <div id="footer">
        <ul>
            <li><a target="_blank" href="pdf/politicacookies.pdf">POLÍTICA DE COOKIES</a></li>
            <li><a target="_blank" href="pdf/politiciaprivacidad.pdf">POLÍTICA DE PRIVACIDAD</a></li>
            <li><a target="_blank" href="pdf/baseslegales.pdf">BASES LEGALES</a></li>
            <li class="ult"><a href="contacto">CONTACTO</a></li>
        </ul>
        <div class="copy">™, ®,© 2019 Kellogg Company</div>
    </div>



    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

ToyStory4/Views/es_ES/Code/Valid.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Código Correcto | Consigue tus pegatinas gratis | Kellogg's</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1">
    <meta name="robots" value="noindex" />

    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/img/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/Content/css/bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/styles.css">
    <style type="text/css">
        .txtsubIndex {
            margin: 60px auto 35px auto
        }

        .divindex {
            margin-bottom: 40px
        }
    </style>
</head>
<body>
    <div class="content  contentKellogs">
        <div class="container containerKellogs">
            <div class="divindex">
                <div class="logo"><img src="~/Content/img/logo.png" alt="Kellog's" clasS="img-fluid" /></div>

                <div class="txtsubIndex">Tu codigo es correcto, para continuar selecciona una de las siguientes opciones:</div>

                @Html.ActionLink("Ya estoy registrado", "Login", "es_ES", null, new { @class = "btn btnEnviar" })
                @Html.ActionLink("No estoy registrado", "Register", "es_ES", null, new { @class = "btn btnEnviar" })
            </div>
            <div class="imgpegat"><img src="~/Content/img/pegatinas.png" alt="pegatinas gratis" /></div>
            <div class="imgpegat_tablet"><img src="~/Content/img/pegatinas_tablet.png" alt="pegatinas gratis" class="img-fluid" /></div>
            <div class="imgpegat_smart"><img src="~/Content/img/pegatinas_smart.png" alt="pegatinas gratis" class="img-fluid" /></div>
        </div>
        <div id="imgcoc"><img src="~/Content/img/cocina.png" alt="cocina disney"></div>
    </div>

    <div id="footer">
        <ul>
            <li><a target="_blank" href="pdf/politicacookies.pdf">POLÍTICA DE COOKIES</a></li>
            <li><a target="_blank" href="pdf/politiciaprivacidad.pdf">POLÍTICA DE PRIVACIDAD</a></li>
            <li><a target="_blank" href="pdf/baseslegales.pdf">BASES LEGALES</a></li>
            <li class="ult"><a href="contacto">CONTACTO</a></li>
        </ul>
        <div class="copy">™, ®,© 2019 Kellogg Company</div>
    </div>



    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

ToyStory4/Views/es_ES/Congrats.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Enhorabuena | Consigue tus pegatinas gratis | Kellogg's</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1">
    <meta name="robots" value="noindex" />


    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/img/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/Content/css/bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/styles.css">
    <style type="text/css">
        .txtsubIndex {
            margin: 30px auto 35px auto
        }

        .divindex {
            margin-bottom: 40px
        }
    </style>
</head>
<body>
    <div class="content  contentKellogs">
        <div class="container containerKellogs">
            <div class="divindex">
                <div class="logo"><img src="~/Content/img/logo.png" alt="Kellog's" clasS="img-fluid" /></div>

                <div class="txtIndex">ENHORABUENA</div>
                <div class="txtsubIndex">Se ha recibido tu participación correctamente, vamos a enviar tu regalo por correo postal.<br><br>¡Atento a tu buzón! :-)</div>

                @Html.ActionLink("Finalizar", "Index", "es_ES", null, new { @class = "btn btnEnviar" })
            </div>
            <div class="imgpegat"><img src="~/Content/img/pegatinas_especial.png" alt="pegatinas gratis" /></div>
            <div class="imgpegat_tablet"><img src="~/Content/img/pegatinas_tablet_especial.png" alt="pegatinas gratis" class="img-fluid" /></div>
            <div class="imgpegat_smart"><img src="~/Content/img/pegatinas_smart_especial.png" alt="pegatinas gratis" class="img-fluid" /></div>
        </div>
        <div id="imgcoc"><img src="~/Content/img/cocina.png" alt="cocina disney"></div>
    </div>

    <div id="footer">
        <ul>
            <li><a target="_blank" href="pdf/politicacookies.pdf">POLÍTICA DE COOKIES</a></li>
            <li><a target="_blank" href="https://www.kelloggs.es/es_ES/privacy-policy.html">POLÍTICA DE PRIVACIDAD</a></li>
            <li><a target="_blank" href="pdf/baseslegales.pdf">BASES LEGALES</a></li>
            <li class="ult"><a href="https://www.kelloggs.es/es_ES/contact_us_es.html">CONTACTO</a></li>
        </ul>
        <div class="copy">™, ®,© 2019 Kellogg Company</div>
    </div>



    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

ToyStory4/Views/es_ES/Index.cshtml
@model ToyStory4.Model.Codigos_cod
@{
    ViewBag.Title = "Home Page";
}

<div class="content  contentKellogs">
    <div class="container containerKellogs">
        <div class="divindex">
            <div class="logo"><img src="~/Content/img/logo.png" alt="Kellog's" clasS="img-fluid" /></div>
            <div class="txtIndex">
                Consigue tus pegatinas<br>
                ¡gratis!<br>
                Para celebrar el estreno de
                TOY STORY 4
            </div>
            @using (Html.BeginForm("ValidateCode", "es_ES", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="txtsubIndex">Introduce el código promocional que aparece dentro del paquete:</div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @Html.EditorFor(model => model.codigo_cod, new { htmlAttributes = new { @id = "txtcod" } })
                @Html.ValidationMessageFor(model => model.codigo_cod, "", new { @class = "text-danger" })


                <input type="submit" value="Enviar" class="btn btnEnviar" style="font-family: KelloggsSansMedium; font-style: normal; font-weight: 600;" />




            }


        </div>
        <div class="imgpegat"><img src="~/Content/img/pegatinas.png" alt="pegatinas gratis" /></div>
        <div class="imgpegat_tablet"><img src="~/Content/img/pegatinas_tablet.png" alt="pegatinas gratis" class="img-fluid" /></div>
        <div class="imgpegat_smart"><img src="~/Content/img/pegatinas_smart.png" alt="pegatinas gratis" class="img-fluid" /></div>
    </div>
    <div id="imgcoc"><img src="~/Content/img/cocina.png" alt="cocina disney"></div>
</div>



<div id="footer">
    <ul>
        <li><a target="_blank" href="pdf/politicacookies.pdf">POLÍTICA DE COOKIES</a></li>
        <li><a target="_blank" href="https://www.kelloggs.es/es_ES/privacy-policy.html">POLÍTICA DE PRIVACIDAD</a></li>
        <li><a target="_blank" href="pdf/baseslegales.pdf">BASES LEGALES</a></li>
        <li class="ult"><a href="https://www.kelloggs.es/es_ES/contact_us_es.html">CONTACTO</a></li>
    </ul>
    <div class="copy">™, ®,© 2019 Kellogg Company</div>
</div>


<div id="barraaceptacion" style="display: block;">
    <div class="inner">
        <h1>Sus preferencias acerca de las cookies en nuestro sitio web</h1>
        <hr />
        <div style="font-size:14px">
            Las cookies son archivos de datos muy pequeños que se almacenan en su equipo o dispositivo móvil cuando visita algunos sitios web. Se trata de una práctica estándar en los sitios web.<br><br>

            Es fundamental que utilicemos cookies para proporcionar una experiencia de calidad elevada y hacer que nuestro sitio web sea más sencillo de utilizar. Por ejemplo, utilizamos las cookies para recopilar estadísticas sobre cómo se utiliza el sitio web y para realizar también un seguimiento de sus preferencias. Puede eliminar las cookies ya almacenadas en el equipo en cualquier momento, al eliminar las cookies podría dejar de disfrutar de la mejor experiencia y de utilizar partes de nuestro sitio web.
        </div>
        <br />
        <a href="#" class="ok" onclick="PonerCookie();">Acepto todas las cookies de este sitio web</a>
        <br> <br><hr>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script>
    function getCookieLOPD(c_name) {
        var c_value = document.cookie;
        var c_start = c_value.indexOf(" " + c_name + "=");
        if (c_start == -1) {
            c_start = c_value.indexOf(c_name + "=");
        }
        if (c_start == -1) {
            c_value = null;
        } else {
            c_start = c_value.indexOf("=", c_start) + 1;
            var c_end = c_value.indexOf(";", c_start);
            if (c_end == -1) {
                c_end = c_value.length;
            }
            c_value = unescape(c_value.substring(c_start, c_end));
        }
        return c_value;
    }

    function setCookieLOPD(c_name, value, exdays) {
        var exdate = new Date();
        exdate.setDate(exdate.getDate() + exdays);
        var c_value = escape(value) + ((exdays == null) ? "" : "; expires=" + exdate.toUTCString());
        document.cookie = c_name + "=" + c_value;
    }

    document.getElementById("barraaceptacion").style.display = "none";

    if (getCookieLOPD('LOPDaviso') != "1") {
        document.getElementById("barraaceptacion").style.display = "block";
    }

    function PonerCookie() {
        setCookieLOPD('LOPDaviso', '1', 365);
        document.getElementById("barraaceptacion").style.display = "none";
    }
</script>

ToyStory4/Views/es_ES/Sorry.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lo Sentimos | Consigue tus pegatinas gratis | Kellogg's</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1">
    <meta name="robots" value="noindex" />


    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/img/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/Content/css/bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/styles.css">
    <style type="text/css">
        .txtsubIndex {
            margin: 30px auto 35px auto
        }

        .divindex {
            margin-bottom: 40px
        }
    </style>
</head>
<body>
    <div class="content  contentKellogs">
        <div class="container containerKellogs">
            <div class="divindex">
                <div class="logo"><img src="~/Content/img/logo.png" alt="Kellog's" clasS="img-fluid" /></div>


                <div class="txtIndex">LO SENTIMOS...</div>
                <div class="txtsubIndex">Se han entregado todas las pegatinas</div>

                @Html.ActionLink("Finalizar", "Index", "es_ES", null, new { @class = "btn btnEnviar" })
            </div>
            <div class="imgpegat"><img src="~/Content/img/pegatinas_especial.png" alt="pegatinas gratis" /></div>
            <div class="imgpegat_tablet"><img src="~/Content/img/pegatinas_tablet_especial.png" alt="pegatinas gratis" class="img-fluid" /></div>
            <div class="imgpegat_smart"><img src="~/Content/img/pegatinas_smart_especial.png" alt="pegatinas gratis" class="img-fluid" /></div>
        </div>
        <div id="imgcoc"><img src="~/Content/img/cocina.png" alt="cocina disney"></div>
    </div>

    <div id="footer">
        <ul>
            <li><a target="_blank" href="pdf/politicacookies.pdf">POLÍTICA DE COOKIES</a></li>
            <li><a target="_blank" href="https://www.kelloggs.es/es_ES/privacy-policy.html">POLÍTICA DE PRIVACIDAD</a></li>
            <li><a target="_blank" href="pdf/baseslegales.pdf">BASES LEGALES</a></li>
            <li class="ult"><a href="https://www.kelloggs.es/es_ES/contact_us_es.html">CONTACTO</a></li>
        </ul>
        <div class="copy">™, ®,© 2019 Kellogg Company</div>
    </div>



    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

ToyStory4/Views/pt_PT/Code/Invalid.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Código Incorreto | Obtenha os seus autocolantes grátis | Kellogg's</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1">
    <meta name="robots" value="noindex" />

    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/img/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/Content/css/bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/styles.css">
    <style type="text/css">
        .txtsubIndex {
            margin: 60px auto 35px auto
        }

        .divindex {
            margin-bottom: 40px
        }
    </style>
</head>
<body>
    <div class="content  contentKellogs">
        <div class="container containerKellogs">
            <div class="divindex">
                <div class="logo"><img src="~/Content/img/logo.png" alt="Kellog's" clasS="img-fluid" /></div>

                <div class="txtsubIndex">O seu código está correto, para continuar selecione uma das seguintes opções:</div>
                @Html.ActionLink("Volver","Index", "pt_PT", null,new { @class="btn btnEnviar"})
            </div>
            <div class="imgpegat"><img src="~/Content/img/pegatinas.png" alt="autocolantes grátis" /></div>
            <div class="imgpegat_tablet"><img src="~/Content/img/pegatinas_tablet.png" alt="autocolantes grátis" class="img-fluid" /></div>
            <div class="imgpegat_smart"><img src="~/Content/img/pegatinas_smart.png" alt="autocolantes grátis" class="img-fluid" /></div>
        </div>
        <div id="imgcoc"><img src="~/Content/img/cocina.png" alt="cocina disney"></div>
    </div>

    <div id="footer">
        <ul>
        <li><a target="_blank" href="">POLÍTICA DE COOKIES</a></li>
        <li><a target="_blank" href="https://www.kelloggs.pt/pt_PT/privacy-policy.html">POLITICA DE PRIVACIDADE</a></li>
        <li><a target="_blank" href="">TERMOS E CONDIÇÕES</a></li>
        <li class="ult"><a href="https://www.kelloggs.pt/pt_PT/contact_us_pt.html">CONTACTO</a></li>
        </ul>
        <div class="copy">™, ®,© 2019 Kelloggs Company</div>
    </div>



    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

ToyStory4/Views/pt_PT/Code/Valid.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Código Correto | Obtenha os seus autocolantes grátis| Kellogg's</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1">
    <meta name="robots" value="noindex" />

    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/img/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/Content/css/bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/styles.css">
    <style type="text/css">
        .txtsubIndex {
            margin: 60px auto 35px auto
        }

        .divindex {
            margin-bottom: 40px
        }
    </style>
</head>
<body>
    <div class="content  contentKellogs">
        <div class="container containerKellogs">
            <div class="divindex">
                <div class="logo"><img src="~/Content/img/logo.png" alt="Kellog's" clasS="img-fluid" /></div>

                <div class="txtsubIndex">O seu código está correto, para continuar selecione uma das seguintes opções:</div>

                @Html.ActionLink("Já estou registado", "Login", "pt_PT", null, new { @class = "btn btnEnviar" })
                @Html.ActionLink("Não estou registado", "Register", "pt_PT", null, new { @class = "btn btnEnviar" })
            </div>
            <div class="imgpegat"><img src="~/Content/img/pegatinas.png" alt="autocolantes grátis" /></div>
            <div class="imgpegat_tablet"><img src="~/Content/img/pegatinas_tablet.png" alt="autocolantes grátis" class="img-fluid" /></div>
            <div class="imgpegat_smart"><img src="~/Content/img/pegatinas_smart.png" alt="autocolantes grátis" class="img-fluid" /></div>
        </div>
        <div id="imgcoc"><img src="~/Content/img/cocina.png" alt="cocina disney"></div>
    </div>

    <div id="footer">
        <ul>
        <li><a target="_blank" href="">POLÍTICA DE COOKIES</a></li>
        <li><a target="_blank" href="https://www.kelloggs.pt/pt_PT/privacy-policy.html">POLITICA DE PRIVACIDADE</a></li>
        <li><a target="_blank" href="">TERMOS E CONDIÇÕES</a></li>
        <li class="ult"><a href="https://www.kelloggs.pt/pt_PT/contact_us_pt.html">CONTACTO</a></li>
        </ul>
        <div class="copy">™, ®,© 2019 Kelloggs Company</div>
    </div>



    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>